import { ArrowDownTrayIcon } from './Icon';
import type { ImageCardProps } from '~/types';

export function ImageCard({ result, onImageClick, label }: ImageCardProps & { label?: string }) {
    const handleDownload = () => {
        const safePrompt = result.metadata.prompt.slice(0, 50).replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '');
        const filename = `${safePrompt}_${Date.now()}.png`;
        const link = document.createElement('a');
        link.href = `data:image/png;base64,${result.image_base64}`;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    return (
        <div className="w-40 h-40 bg-gray-900 rounded-md flex flex-col justify-between relative">
            <button type="button" className="block w-full h-full text-left rounded-md focus:outline-none focus-visible:ring-2 focus-visible:ring-purple-500 flex items-center justify-center" onClick={() => onImageClick(result)}>
                <img
                    src={`data:image/png;base64,${result.image_base64}`}
                    alt={`Generated by ${result.metadata.model_id}`}
                    className="max-w-full max-h-full object-contain rounded-md shadow-md transition-transform hover:scale-105"
                />
            </button>
            {label && (
                <div className="bg-gray-800 text-purple-400 text-xs rounded px-2 py-0.5 mb-1 mx-auto w-fit">
                    {label}
                </div>
            )}
            <div className="p-1 bg-gray-900/50 rounded-b-md">
                <div className="flex justify-between items-center">
                    <p className="text-xs text-gray-400 font-mono truncate mr-2">
                        {result.metadata.model_id}
                    </p>
                    <button
                        onClick={handleDownload}
                        className="p-1 bg-gray-700 hover:bg-purple-600 rounded-md transition-colors"
                        title="Tải ảnh xuống"
                    >
                        <ArrowDownTrayIcon className="w-4 h-4 text-white" />
                    </button>
                </div>
            </div>
        </div>
    );
}